tripobeat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tripobeatApp.urls', namespace='tripobeat')),
    path('users/', include('users.urls', namespace='users')),
]

tripobeatApp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'tripobeatApp'
#url patterns has list of all urls corresponding to the views and the webpages
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('home/', views.alternate_page, name = 'alternate_page'),
    path('blog/', views.blog_page, name = 'blog_page'),
    path('itineraries/', views.category_page, name = 'category_page'),
    path('itineraries/<int:itinerary_id>/', views.item_page, name = 'item_page'),
    path('itineraries/search/', views.search_result, name = 'search_result'),
    path('itineraries/add/', views.add_category, name='add_category'),
    path('itineraries/<int:itinerary_id>/delete/', views.delete_category, name = 'delete_category'),
    path('itineraries/<int:itinerary_id>/edit/', views.edit_category, name = 'edit_category'),
    path('itineraries/add_item/', views.add_item_page, name='add_item_page'),
    path('get_other_blogs/', views.get_other_blogs, name='get_other_blogs'),
    path('itineraries/<int:itinerary_id>/delete_review/<int:review_id>/', views.delete_review, name='delete_review'),
    path('itineraries/<int:itinerary_id>/edit_review/<int:review_id>/', views.edit_review, name='edit_review'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'
#url patterns has list of all urls corresponding to the views and the webpages
urlpatterns = [
    path('', views.login, name = 'login'),
    path('login/', views.login_page, name = 'login_page'),
    path('logout/', views.logout_page, name= 'logout'),
    path('register/', views.register, name = 'register'),
    path('profile/<str:username>', views.profile, name = 'profile'),
    #path('editprofile/<str:username>', views.edit_profile, name = 'edit_profile'),
    path('userprofiles/', views.user_profiles, name = 'user_profiles'),
]

tripobeatApp/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
# Class and Objects for Blog Page
class BlogPost(models.Model):
    title = models.CharField(max_length= 200)
    description = models.TextField()

# Class and Objects for Category Page
class Category(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    cost = models.TextField()
    image_url = models.ImageField(upload_to='images/')
    departure_details = models.TextField(default = '')
    return_details = models.TextField(default = '')
    inclusions = models.TextField(default = '')
    exclusions = models.TextField(default = '')
    access = models.TextField(default = '')
    cancel = models.TextField(default = '')
    author = models.CharField(default= "Pranav")
    date_posted = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tripobeatApp:item_page', args=[self.id])

# Class and Objects for Item Page
class Item(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    departure_details = models.TextField()
    return_details = models.TextField()
    inclusions = models.TextField()
    exclusions = models.TextField()
    access = models.TextField()
    cancel = models.TextField()
    image_url = models.ImageField(upload_to='images/')
    author = models.CharField(default= "Pranav")
    date_posted = models.DateTimeField(default = timezone.now)


# Class and Objects for Item Page Reviews
class Review(models.Model):
    name = models.ForeignKey(User, on_delete= models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    item = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.item.title

    def get_absolute_url(self):
        return reverse('tripobeatApp:item_page', args=[self.item_id])


# Class and Objects for Home Page
class Search(models.Model):
    place = models.TextField()

regular_user = {"username": "Pranav", "password": "Pranav"}
admin_user = {"username": "admin", "password": "admin"}

tripobeatApp/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'description']

tripobeatApp/views.py
from django.shortcuts import render, redirect
from .models import admin_user,regular_user, Category, BlogPost, Search, Item, Review
from django.contrib import messages
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from .forms import ReviewForm
from actions.models import Action

#home page view is used to render the home page
def home_page(request):
    return render(request, 'tripobeatApp/travel/index.html')

#alternate page view is used to render the home page after user is logged in
def alternate_page(request):
    searches = Search.objects.all()
    actions = Action.objects.all().order_by('-created')
    print(actions)
    return render(request, 'tripobeatApp/travel/alternate.html', {"searches": searches, "actions": actions})

#blog page view is used to render the blog page.
def blog_page(request):
    return render(request, 'tripobeatApp/travel/blog.html')

def get_other_blogs(request):
    blogs = BlogPost.objects.all()
    blog_data = [{'title': blog.title, 'description': blog.description} for blog in blogs]
    print(blog_data)
    return JsonResponse({'blogs': blog_data})

#category page view is used to render the list view of itineraries
def category_page(request):
    categories = Category.objects.all().order_by("id")
    return render(request, 'tripobeatApp/travel/category.html', {"categories": categories})

#item page view displays a single selected itineraries from a list of itineraries
def item_page(request, itinerary_id):
    itinerary = get_object_or_404(Category, id=itinerary_id)
    reviews = list(Review.objects.filter(item=itinerary_id).order_by('-date_posted'))
    if request.method == 'POST':
        username = request.session.get('username')
        user = User.objects.get(username=username)
        title = request.POST.get('title', '')
        description = request.POST.get('description', '')
        review = Review.objects.create(name=user, title=title, description=description, item=itinerary)
        review_title = review.title
        try:
            reviews.append(review)
            action = Action(
                user=user,
                verb="has created a review named " + review_title + " for the product",
                target=itinerary
            )
            action.save()
        except Category.DoesNotExist:
            pass
    reviews = Review.objects.filter(item = itinerary_id).order_by('-date_posted')
    return render(request, 'tripobeatApp/travel/item.html', {"items": itinerary, "reviews": reviews})

def edit_review(request, review_id, itinerary_id):
    review = get_object_or_404(Review, id=review_id)
    itinerary_name = Category.objects.get(id=itinerary_id)
    user = User.objects.get(username=request.session.get('username'))
    review_title = review.title
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            action = Action(
                user=user,
                verb="has edited review with title: " + review.title + " for product:",
                target=review
            )
            action.save()
            return redirect('tripobeatApp:item_page', itinerary_id=review.item.id)
    else:
        form = ReviewForm(instance=review)
    return render(request, "tripobeatApp/travel/edit_review.html", {"form": form, "review": review})


def delete_review(request, review_id, itinerary_id):
    review = get_object_or_404(Review, id=review_id)
    itinerary_name = Category.objects.get(id=itinerary_id)
    review_title = review.title
    print(review_title)
    user = User.objects.get(username=request.session.get('username'))
    if request.session.get('username') == review.name.username or request.session.get('access') == 'admin':
        print(review_title)
        action = Action(
            user=user,
            verb="has deleted review: " + review_title,
            target=review
        )
        action.save()
        review.delete()
    number_of_objects = Review.objects.count()
    if number_of_objects == 0:
        return JsonResponse({'success': True, 'deleted_review_id': review_id, 'no_reviews': 0})
    return JsonResponse({'success': True, 'deleted_review_id': review_id})


#search result view is to display the simulated search feature
def search_result(request):
    text_input = request.GET.get('text-input', '').lower()
    if text_input == 'blacksburg':
        return render(request, 'tripobeatApp/travel/category.html', {"categories": categories})
    else:
        return render(request, 'tripobeatApp/travel/search_result.html', {"title": text_input})

#add category view is to demonstrate add view functionality
def add_category(request):
    if request.method == 'POST':
        place_name = request.POST['place_name']
        description = request.POST['description']
        days_price = request.POST['days_price']
        image_url = request.FILES['image_url'] if 'image_url' in request.FILES else None
        departure_details = request.POST['departure_details']
        exclusions_string = request.POST['exclusion']
        return_details = request.POST['return_details']
        #exclusions_string = "Lunch & Dinner, Anything not mentioned in the Inclusions"
        inclusions_string = request.POST['inclusion']
        access_string = request.POST['access']
        cancel_string = request.POST['cancel']
        user = User.objects.get(username=request.session.get('username'))
        new_category = Category(
            title=place_name,
            description=description,
            cost=days_price,
            image_url=image_url,
            author = request.session.get('username'),
            departure_details = departure_details,
            return_details = return_details,
            inclusions = inclusions_string,
            exclusions = exclusions_string,
            access = access_string,
            cancel = cancel_string,
        )
        title_save = new_category.title
        if image_url:
            new_category.image_url = image_url

        new_category.save()
        action = Action(
            user=user,
            verb=f"has created a new Itinerary named- '{title_save}': Link- ",
            target=new_category
        )
        action.save()
        messages.add_message(request, messages.SUCCESS, "You have added new itinerary successfully: %s" % new_category.title)
        return redirect('tripobeatApp:item_page', itinerary_id = new_category.id)
    categories= Category.objects.all()
    print(place_name, description, days_price, image_url, departure_details, return_details, inclusion, exclusion,
          access, cancel)
    return render(request, 'tripobeatApp/travel/category.html', {'categories': categories})

#edit category view is to demonstrate edit view functionality
def edit_category(request, itinerary_id):
    user = User.objects.get(username=request.session.get('username'))
    category = Category.objects.get(id=itinerary_id)
    if request.method == 'POST':
        old_name = category.title
        old_description = category.description
        category.title = request.POST.get('title')
        category.description = request.POST.get('description');
        category.cost = request.POST.get('cost');
        category.departure_details = request.POST['departure_details']
        category.exclusions = request.POST['exclusion']
        category.return_details = request.POST['return_details']
        # exclusions_string = "Lunch & Dinner, Anything not mentioned in the Inclusions"
        category.inclusions = request.POST['inclusion']
        category.access = request.POST['access']
        category.cancel = request.POST['cancel']
        if old_name != category.title:
            action_name = f"has edited the title from '{old_name}' to '{category.title}'- Link: "
        else:
            action_name = None
        if old_description != category.description:
            action_description = f"has edited the description from '{old_description}' to '{category.description}'- Link:"
        else:
            action_description = None
        category.save()
        if action_name:
            action_title_instance = Action(
                user=user,
                verb=action_name,
                target=category
            )
            action_title_instance.save()
        if action_description:
            action_price_instance = Action(
                user=user,
                verb=action_description,
                target=category
            )
            action_price_instance.save()
        messages.add_message(request, messages.INFO, "You have edited an itinerary: %s" % old_name)
        redirect_url = reverse('tripobeatApp:item_page', kwargs={'itinerary_id': itinerary_id})
        return HttpResponseRedirect(redirect_url)
    return render(request, 'tripobeatApp/travel/edit_item.html', {'category': category})

#delete category view is to demonstrate delete view functionality
def delete_category(request, itinerary_id):
    user = User.objects.get(username=request.session.get('username'))
    place = Category.objects.get(id = itinerary_id)
    action = Action(
        user=user,
        verb="has deleted the Itinerary:" + place.title,
        target=place
    )
    action.save()
    place.delete()
    messages.add_message(request, messages.WARNING, "You have deleted the itinerary: %s" % place.title)
    return redirect('tripobeatApp:category_page')

def add_item_page(request):
    return render(request, 'tripobeatApp/travel/add_item.html')

templates/tripobeatApp/travel/add_item.html
{% extends "tripobeatApp/base.html" %}
{% load static %}
{%  block page-title %} index {% endblock %}
{% block content-text-block %}
    {% if request.session.access == 'admin' %}
        <div class = "add-form-flex">
        <div id="add-form" class="add-form">
            <form method="post" action="{% url 'tripobeatApp:add_category' %}" enctype="multipart/form-data" class = "add-form-outer">
                {% csrf_token %}
                <div class = "add-div">
                <div>
                <label for="place_name">Place Name:</label>
                <input type="text" name="place_name" class = "add-input" required>
                </div>
                <div>
                <label for="description">Description:</label>
                <input type="text" name="description" class = "add-input" required>
                </div>
                <div>
                <label for="days_price">Days and Price:</label>
                <input type="text" name="days_price" class = "add-input" required>
                </div>
                <div>
                <label for="image_url">Image:</label>
                <input type="file" name="image_url" class = "add-input">
                </div>
                    <div>
                <label for="departure_details">Departure Details:</label>
                <input type="text" name="departure_details" class = "add-input">
                </div>
                    <div>
                <label for="return_details">Return Details:</label>
                <input type="text" name="return_details" class = "add-input">
                </div>
                    <div>
                <label for="inclusion">Inclusions:</label>
                <input type="text" name="inclusion" class = "add-input">
                </div>
                    <div>
                <label for="exclusion">Exclusions:</label>
                <input type="text" name="exclusion" class = "add-input">
                </div>
                    <div>
                <label for="access">Accesibility Information:</label>
                <input type="text" name="access" class = "add-input">
                </div>
                    <div>
                <label for="cancel">Cancellation Policy:</label>
                <input type="text" name="cancel" class = "add-input">
                </div>
                 </div>
                <div class = "submit-add-button-div">
                <button type="submit" class = "submit-add-button">Submit</button>
                </div>
            </form>
        </div>
        </div>

    {% endif %}
{%  endblock %}

templates/tripobeatApp/travel/alternate.html
{% extends "tripobeatApp/base.html" %}
{% load static %}
{%  block page-title %} index {% endblock %}
{% block content-text-block %}
    <div class = "content">
<div class="content-text-alternate">
            <div class = "recent-activity-home">
            {% include "actions/action/feed.html" %}
            </div>
            <div class="cta-div-alternate">
                <a href="{% url "tripobeat:category_page" %}" class="cta-a"> Start Exploring! Let's Go </a>
            </div>
        </div>
    </div>
{%  endblock %}

templates/tripobeatApp/travel/category.html
{% extends "tripobeatApp/base.html" %}
{% load static %}
{% block page-title %} index {% endblock %}
{% block content-text-block %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src= "{% static "js/category.js" %}" ></script>
    <div class="category-content">
        <div class="city-description">
            <h1>Things to do near Blacksburg</h1>
        </div>
        <div class="city-description-wrapper">
            <h2>Itineraries</h2>
            {% if request.session.access == 'admin' %}
            <a href="{% url 'tripobeatApp:add_item_page'%}" class="add-item">Add new item</a>
            {% endif %}
        <button id="sort-by-title" class = "sort-item" onclick="sortCategoriesByTitle()">Sort by Name</button>
        </div>
        {% if categories %}
        <div class="items-grid">
            {% for category in categories %}
                <div class="categories" data-title="{{ category.title }}">
                    <div class="heart-wrapper">
                        {% if category.image_url %}
                             <img class="place-image" alt="place-image" src="{{ category.image_url.url }}">
                        {% else %}
                            <img class="placeholder-image" alt="placeholder-image" src="{% static 'NRG_3.jpeg' %}">
                        {% endif %}
                        <i class="fa fa-heart" aria-hidden="true"></i>
                        {% if request.session.access == 'admin' %}
                        <div id="edit-form-{{ itinerary.id }}" class = "edit-form-div-outer">
                            <a class = "edit-btn" href = "{% url 'tripobeat:edit_category' category.id %}"> Edit Itinerary</a>
                        </div>
                        {% endif %}
                    </div>

                    <div class="place-description">

                        <div class = "delete-div">
                        <a class="place-name">{{ category.title }}</a>
                            {% if request.session.access == 'admin' %}
                        <form method="post" class= "delete-form" action="{% url 'tripobeat:delete_category' category.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="itinerary_id" value="{{ category.id }}">
                         <button type="submit" class ="delete-button" onclick="confirmDelete('{{ category.id }}')">Delete</button>
                        </form>
                            {% endif %}
                        </div>

                        <p>{{ category.description }}</p>
                        <a>{{ category.cost }}</a>
                        <div class="cta-button-category-div">
                            <a href="{% url 'tripobeatApp:item_page' category.id %}" class="cta-button-category">Let's Go!</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
            {% else %}
            <div class = "friendly-ext-div">
            <div class="friendly-message">
            No itineraries at the moment. Add new itineraries to display!
            </div>
            </div>
        {% endif %}
    </div>
 {% endblock %}

templates/tripobeatApp/travel/index.html
{% extends "tripobeatApp/base.html" %}
{% load static %}
{%  block page-title %} index {% endblock %}
{% block content-text-block %}
    <div class = "content">
 <div class="content-text">
            <div class="Tripobeat-help-div">
                <h1 class="Tripobeat-help"> How Tripobeat Works? </h1>
            </div>
            <div class="site-description">
                <div class="site-description-each">
                    <i class="fa fa-globe" aria-hidden="true"></i>
                    <p> Select your destination from a list of our many curated destinations</p>
                </div>
                <div class="site-description-each">
                    <i class="fa fa-building"  aria-hidden="true"></i>
                    <p> Select your accomodation choice from our list of 100+ accomodations</p>
                </div>
                <div class="site-description-each">
                    <i class="fa fa-usd" aria-hidden="true"></i>
                    <p> Select a budget that doesn't burn a hole in your pocket</p>
                </div>
                <div class="site-description-each">
                    <i class="fa fa-sticky-note-o" aria-hidden="true"></i>
                    <p> Finish your iternary and enjoy your trip. It's that simple! </p>
                </div>
            </div>
            <div class="cta-div">
                <a href="{% url "tripobeat:category_page" %}" class="cta-a">
                    Start Exploring! Let's Go
                </a>
            </div>
        </div>
    </div>
{%  endblock %}

templates/tripobeatApp/travel/item.html
{% extends "tripobeatApp/base.html" %}
{% load static %}
{% load tz %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{%  block page-title %} index {% endblock %}
{% block content-text-block %}
        <div class="item-content">
        <div class = "title-edit">
        <h1 class="item-name"> {{ items.title }} </h1>
            {% if request.session.access == 'admin' %}
            <a class = "edit-btn" href = "{% url 'tripobeat:edit_category' items.id %}"> Edit </a>
            {% endif %}
        </div>

        <div class="nav-bar-item">
            <ul class="nav-bar-list-item">
                <li><a href="#about" class="nav-item-button">Overview</a></li>
                <li><a href="#reviews" class="nav-item-button">Reviews </a></li>
            </ul>
        </div>
        {% if request.session.access == 'admin' %}
        <div>
            Posted by {{ items.author }} on {{ items.date_posted|timezone:"US/Eastern"|date:"F j, Y P" }}
        </div>
        {% endif %}
        <!-- Horizontal Scrolling Images for the Location-->
<div class="scrolling-images">
    <div class="image-container">
        {% if items.image_url %}
            <img src="{{ items.image_url.url }}" alt="{{ items.title }}" style="max-width: 100%; max-height: 100%; height: auto; width: 100%;" />
        {% else %}
             <img src="{% static 'NRG_3.jpg' %}" alt="Default Image" style="max-width: 100%; max-height: 100%; height: auto; width: 100%;" />
        {% endif %}
    </div>
</div>
        <!--- Location Description -->
        <div class="item-flex">
            <div class="item-description">
                <a class="list-utext" id="about">About</a>
                <p> {{ items.description }}</p>
                <hr class="solid">
                <div class="dropdown-container">
                    <div class="dropdown">
                        <button class="dropdown-toggle"> Departure and return <i class="fa fa-caret-down"
                                aria-hidden="true"></i> </button>
                        <ul class="lists">

                            <li> <a class="list-utext" class="list-toggle"> Departure details </a> </li>

                            <li> <a> {{ items.departure_details}}
                                </a> </li>

                            <li> <a class="list-utext"> Return details</a> </li>

                            <li> <a>
                                {{items.return_details}}
                                </a> </li>
                        </ul>
                    </div>
                    <!-- Dropdown to hide multiple windows like Inclusions, Exclusions etc-->
                    <hr class="solid">
                    <div class="dropdown">
                        <button class="dropdown-toggle" id="inclusions"> Inclusions <i class="fa fa-caret-down"
                                aria-hidden="true"></i> </button>
                        <ul class="lists">
                            <li> {{ items.inclusions }}</li>
                        </ul>


                    </div>
                    <hr class="solid">
                    <div class="dropdown">
                        <button class="dropdown-toggle"> Exclusions <i class="fa fa-caret-down" aria-hidden="true"></i>
                        </button>

                        <ul class="lists">
                            <li> {{ items.exclusions }}</li>
                        </ul>

                    </div>
                    <hr class="solid">
                    <div class="dropdown">
                        <button class="dropdown-toggle"> Accesibility <i class="fa fa-caret-down"
                                aria-hidden="true"></i>
                        </button>
                        <ul class="lists">
                            <li> {{ items.access }}</li>
                        </ul>

                    </div>
                    <hr class="solid">
                    <div class="dropdown">
                        <button class="dropdown-toggle"> Cancellation Policy <i class="fa fa-caret-down"
                                aria-hidden="true"></i> </button>
                        <div class="lists">{{ items.cancel }}</div>
                    </div>
                </div>
            </div>
            <!-- Book the package, reserve spot. -->
            <div class="cart-addition">
                <a class="list-utext"> Reserve your Spot </a>
                <div class="cal-users">
                    <a> Enter your preferred date of travel </a>
                    <input type="text" id="date-input" placeholder="MM/DD/YYYY" class="search-bar date-box">
                    <label for="Users"><i class="fa fa-user" aria-hidden="true"> </i>No of people</label>
                    <select id="Users" class="users-box">
                        <option value="1"> 1 </option>
                        <option value="2"> 2 </option>
                        <option value="3"> 3 </option>
                        <option value="4"> 4 </option>
                        <option value="5"> 5 </option>
                        <option value="6"> 6 </option>
                        <option value="7"> 7 </option>
                        <option value="8"> 8 </option>
                        <option value="9"> 9 </option>
                        <option value="10"> 10 </option>
                    </select>
                </div>
                <div class="product">
                    <div><button class="cta-atc" id="addtoCart"> Add to cart </button></div>
                    <div id="placeholderaddSuccess"> </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Reviews Section -->
    <div class="reviews-total">
        <hr class="solid">
        <a class="reviews-header"> Reviews</a>
        <div>
            <div class="reviews">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <a href="#more-reviews" class="more-reviews"> 4.0/5.0 (29 Reviews) </a>
                {% if request.session.username %}
                <button class="nav-item-button leave-a-review" id="leave-review-button"> Leave a Review </button>
                    {% endif %}
            </div>
            <form id="review-form" style="display: none;">
                {% csrf_token %}
            <input type="text" name="title" placeholder="Review Title" />
            <textarea name="description" placeholder="Your Review" rows="4"></textarea>
                <input type="hidden" name="itinerary-id" value= {{ items.id }} />
            <input type="hidden" name="review_id" value="{{ review.id }}">
            <button type="submit">Submit Review</button>

            </form>
            <hr class='dotted'>
            <div class="ind-review" id="reviews">
            {% if reviews %}
                {% for review in reviews %}
              <div class = "edit-delete-buttons-flex">
                <div class = "ind-review-new">
                <a href = "{% url 'users:profile' review.name.username %}" class="reviewer-name"> {{ review.name }} </a>
                <div class="ind-review-description">
                    <div class="ind-review-div">
                        <p class="ind-review-header"> {{ review.title }}</p>
                        <p>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <!-- Used Inline styling here, since it is a single property for half star -->
                            <i class="fa fa-star-half-o" style="font-size: 15px;" aria-hidden="true"></i>
                        </p>
                    </div>
                    <p> {{ review.description }}</p>
                    <p>{{ review.date_posted|timezone:"US/Eastern"|date:"F j, Y P" }}</p>
                    <hr class = "solid">
                    </div>
                </div>

                {% if request.session.access == 'admin' or request.session.username == review.name.username %}
                <div class="review-actions">
                <div><a href="{% url 'tripobeatApp:edit_review' itinerary_id=items.id review_id=review.id %}" class = "edit-review-btn">Edit</a></div>
                <div><a href = "#" class="delete-review" data-review-id="{{ review.id }}" data-itinerary-id="{{ items.id }}">Delete</a></div>
                </div>
                {% endif %}
              </div>
                {% endfor %}
            {% else %}
            <div class = "no-comments">
                No reviews for this product yet!
            </div>
            {% endif %}
            </div>


        </div>
    </div>
{%  endblock %}