tripobeat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tripobeatApp.urls', namespace='tripobeat')),
    path('users/', include('users.urls', namespace='users')),
]

tripobeatApp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'tripobeatApp'
#url patterns has list of all urls corresponding to the views and the webpages
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('home/', views.alternate_page, name = 'alternate_page'),
    path('blog/', views.blog_page, name = 'blog_page'),
    path('itineraries/', views.category_page, name = 'category_page'),
    path('itineraries/<int:itinerary_id>/', views.item_page, name = 'item_page'),
    path('itineraries/search/', views.search_result, name = 'search_result'),
    path('itineraries/add/', views.add_category, name='add_category'),
    path('itineraries/<int:itinerary_id>/delete/', views.delete_category, name = 'delete_category'),
    path('itineraries/<int:itinerary_id>/edit/', views.edit_category, name = 'edit_category'),
    path('itineraries/add_item/', views.add_item_page, name='add_item_page'),
    path('get_other_blogs/', views.get_other_blogs, name='get_other_blogs'),
    path('itineraries/<int:itinerary_id>/delete_review/<int:review_id>/', views.delete_review, name='delete_review'),
    path('itineraries/<int:itinerary_id>/edit_review/<int:review_id>/', views.edit_review, name='edit_review'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'
#url patterns has list of all urls corresponding to the views and the webpages
urlpatterns = [
    path('', views.login, name = 'login'),
    path('login/', views.login_page, name = 'login_page'),
    path('logout/', views.logout_page, name= 'logout'),
    path('register/', views.register, name = 'register'),
    path('profile/<str:username>', views.profile, name = 'profile'),
    #path('editprofile/<str:username>', views.edit_profile, name = 'edit_profile'),
    path('userprofiles/', views.user_profiles, name = 'user_profiles'),
]

tripobeatApp/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
# Class and Objects for Blog Page
class BlogPost(models.Model):
    title = models.CharField(max_length= 200)
    description = models.TextField()

# Class and Objects for Category Page
class Category(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    cost = models.TextField()
    image_url = models.ImageField(upload_to='images/')
    departure_details = models.TextField(default = '')
    return_details = models.TextField(default = '')
    inclusions = models.TextField(default = '')
    exclusions = models.TextField(default = '')
    access = models.TextField(default = '')
    cancel = models.TextField(default = '')
    author = models.CharField(default= "Pranav")
    date_posted = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tripobeatApp:item_page', args=[self.id])

# Class and Objects for Item Page
class Item(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    departure_details = models.TextField()
    return_details = models.TextField()
    inclusions = models.TextField()
    exclusions = models.TextField()
    access = models.TextField()
    cancel = models.TextField()
    image_url = models.ImageField(upload_to='images/')
    author = models.CharField(default= "Pranav")
    date_posted = models.DateTimeField(default = timezone.now)


# Class and Objects for Item Page Reviews
class Review(models.Model):
    name = models.ForeignKey(User, on_delete= models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    item = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.item.title

    def get_absolute_url(self):
        return reverse('tripobeatApp:item_page', args=[self.item_id])


# Class and Objects for Home Page
class Search(models.Model):
    place = models.TextField()

regular_user = {"username": "Pranav", "password": "Pranav"}
admin_user = {"username": "admin", "password": "admin"}

tripobeatApp/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'description']

tripobeatApp/views.py
from django.shortcuts import render, redirect
from .models import admin_user,regular_user, Category, BlogPost, Search, Item, Review
from django.contrib import messages
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from .forms import ReviewForm
from actions.models import Action

#home page view is used to render the home page
def home_page(request):
    return render(request, 'tripobeatApp/travel/index.html')

#alternate page view is used to render the home page after user is logged in
def alternate_page(request):
    searches = Search.objects.all()
    actions = Action.objects.all().order_by('-created')
    print(actions)
    return render(request, 'tripobeatApp/travel/alternate.html', {"searches": searches, "actions": actions})

#blog page view is used to render the blog page.
def blog_page(request):
    return render(request, 'tripobeatApp/travel/blog.html')

def get_other_blogs(request):
    blogs = BlogPost.objects.all()
    blog_data = [{'title': blog.title, 'description': blog.description} for blog in blogs]
    print(blog_data)
    return JsonResponse({'blogs': blog_data})

#category page view is used to render the list view of itineraries
def category_page(request):
    categories = Category.objects.all().order_by("id")
    return render(request, 'tripobeatApp/travel/category.html', {"categories": categories})

#item page view displays a single selected itineraries from a list of itineraries
def item_page(request, itinerary_id):
    itinerary = get_object_or_404(Category, id=itinerary_id)
    reviews = list(Review.objects.filter(item=itinerary_id).order_by('-date_posted'))
    if request.method == 'POST':
        username = request.session.get('username')
        user = User.objects.get(username=username)
        title = request.POST.get('title', '')
        description = request.POST.get('description', '')
        review = Review.objects.create(name=user, title=title, description=description, item=itinerary)
        review_title = review.title
        try:
            reviews.append(review)
            action = Action(
                user=user,
                verb="has created a review named " + review_title + " for the product",
                target=itinerary
            )
            action.save()
        except Category.DoesNotExist:
            pass
    reviews = Review.objects.filter(item = itinerary_id).order_by('-date_posted')
    return render(request, 'tripobeatApp/travel/item.html', {"items": itinerary, "reviews": reviews})

def edit_review(request, review_id, itinerary_id):
    review = get_object_or_404(Review, id=review_id)
    itinerary_name = Category.objects.get(id=itinerary_id)
    user = User.objects.get(username=request.session.get('username'))
    review_title = review.title
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            action = Action(
                user=user,
                verb="has edited review with title: " + review.title + " for product:",
                target=review
            )
            action.save()
            return redirect('tripobeatApp:item_page', itinerary_id=review.item.id)
    else:
        form = ReviewForm(instance=review)
    return render(request, "tripobeatApp/travel/edit_review.html", {"form": form, "review": review})


def delete_review(request, review_id, itinerary_id):
    review = get_object_or_404(Review, id=review_id)
    itinerary_name = Category.objects.get(id=itinerary_id)
    review_title = review.title
    print(review_title)
    user = User.objects.get(username=request.session.get('username'))
    if request.session.get('username') == review.name.username or request.session.get('access') == 'admin':
        print(review_title)
        action = Action(
            user=user,
            verb="has deleted review: " + review_title,
            target=review
        )
        action.save()
        review.delete()
    number_of_objects = Review.objects.count()
    if number_of_objects == 0:
        return JsonResponse({'success': True, 'deleted_review_id': review_id, 'no_reviews': 0})
    return JsonResponse({'success': True, 'deleted_review_id': review_id})


#search result view is to display the simulated search feature
def search_result(request):
    text_input = request.GET.get('text-input', '').lower()
    if text_input == 'blacksburg':
        return render(request, 'tripobeatApp/travel/category.html', {"categories": categories})
    else:
        return render(request, 'tripobeatApp/travel/search_result.html', {"title": text_input})

#add category view is to demonstrate add view functionality
def add_category(request):
    if request.method == 'POST':
        place_name = request.POST['place_name']
        description = request.POST['description']
        days_price = request.POST['days_price']
        image_url = request.FILES['image_url'] if 'image_url' in request.FILES else None
        departure_details = request.POST['departure_details']
        exclusions_string = request.POST['exclusion']
        return_details = request.POST['return_details']
        #exclusions_string = "Lunch & Dinner, Anything not mentioned in the Inclusions"
        inclusions_string = request.POST['inclusion']
        access_string = request.POST['access']
        cancel_string = request.POST['cancel']
        user = User.objects.get(username=request.session.get('username'))
        new_category = Category(
            title=place_name,
            description=description,
            cost=days_price,
            image_url=image_url,
            author = request.session.get('username'),
            departure_details = departure_details,
            return_details = return_details,
            inclusions = inclusions_string,
            exclusions = exclusions_string,
            access = access_string,
            cancel = cancel_string,
        )
        title_save = new_category.title
        if image_url:
            new_category.image_url = image_url

        new_category.save()
        action = Action(
            user=user,
            verb=f"has created a new Itinerary named- '{title_save}': Link- ",
            target=new_category
        )
        action.save()
        messages.add_message(request, messages.SUCCESS, "You have added new itinerary successfully: %s" % new_category.title)
        return redirect('tripobeatApp:item_page', itinerary_id = new_category.id)
    categories= Category.objects.all()
    print(place_name, description, days_price, image_url, departure_details, return_details, inclusion, exclusion,
          access, cancel)
    return render(request, 'tripobeatApp/travel/category.html', {'categories': categories})

#edit category view is to demonstrate edit view functionality
def edit_category(request, itinerary_id):
    user = User.objects.get(username=request.session.get('username'))
    category = Category.objects.get(id=itinerary_id)
    if request.method == 'POST':
        old_name = category.title
        old_description = category.description
        category.title = request.POST.get('title')
        category.description = request.POST.get('description');
        category.cost = request.POST.get('cost');
        category.departure_details = request.POST['departure_details']
        category.exclusions = request.POST['exclusion']
        category.return_details = request.POST['return_details']
        # exclusions_string = "Lunch & Dinner, Anything not mentioned in the Inclusions"
        category.inclusions = request.POST['inclusion']
        category.access = request.POST['access']
        category.cancel = request.POST['cancel']
        if old_name != category.title:
            action_name = f"has edited the title from '{old_name}' to '{category.title}'- Link: "
        else:
            action_name = None
        if old_description != category.description:
            action_description = f"has edited the description from '{old_description}' to '{category.description}'- Link:"
        else:
            action_description = None
        category.save()
        if action_name:
            action_title_instance = Action(
                user=user,
                verb=action_name,
                target=category
            )
            action_title_instance.save()
        if action_description:
            action_price_instance = Action(
                user=user,
                verb=action_description,
                target=category
            )
            action_price_instance.save()
        messages.add_message(request, messages.INFO, "You have edited an itinerary: %s" % old_name)
        redirect_url = reverse('tripobeatApp:item_page', kwargs={'itinerary_id': itinerary_id})
        return HttpResponseRedirect(redirect_url)
    return render(request, 'tripobeatApp/travel/edit_item.html', {'category': category})

#delete category view is to demonstrate delete view functionality
def delete_category(request, itinerary_id):
    user = User.objects.get(username=request.session.get('username'))
    place = Category.objects.get(id = itinerary_id)
    action = Action(
        user=user,
        verb="has deleted the Itinerary:" + place.title,
        target=place
    )
    action.save()
    place.delete()
    messages.add_message(request, messages.WARNING, "You have deleted the itinerary: %s" % place.title)
    return redirect('tripobeatApp:category_page')

def add_item_page(request):
    return render(request, 'tripobeatApp/travel/add_item.html')

templates/tripobeatApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Background Image in this Page by Freepik -->
<!-- Base template which is inherited by all the components for header and footer -->
<head>
    <title> Tripobeat | {% block page-title %} {% endblock %} </title>
    <meta charset="utf-8">
    <meta name="description" content="The Homepage for Tripobeat">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src= "{% static "js/scripts.js" %}" ></script>
    <!-- Below library is used for Social Media Icons-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "css/global.css"%}">
    <link rel="stylesheet" href="{% static "css/index.css" %}">
    <link rel="stylesheet" href="{% static "css/alternate.css" %}">
    <link rel="stylesheet" href="{% static "css/blog.css" %}">
    <link rel="stylesheet" href="{% static "css/category.css" %}">
    <link rel="stylesheet" href="{% static "css/item.css" %}">
    <link rel="stylesheet" href="{% static "css/review.css" %}">
    <link rel="stylesheet" href="{% static "css/search_input.css" %}">
</head>

<body>
    <!--Header Code-->
    <header class="header">
        <div class="header-left">
            <!-- Own Logo made on canva using existing tools -->
            <img class="site-logo" alt="site-logo" src="{% static "images/Tripobeat-logo.png" %}">
        </div>
        <div class="header-center">
            <form action=" {% url 'tripobeatApp:search_result' %}" method="GET">
                <input type="text" placeholder="Places to go, Things to do" class="search-bar" name = "text-input">
                <button class="search-button"> Search </button>
            </form>
        </div>
        <div class="header-right">
            <i class="fa fa-heart" aria-hidden="true"></i>
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            {% if request.session.username %}
                <div class="user-dropdown">
                <a class="login">{{ request.session.username }}</a>
                <div class="dropdown-content">
                    <a href="{% url "users:profile" request.session.username %}">Profile</a>
                    <a href="{% url "users:user_profiles" %}">All users profiles</a>
                    <a class="logout" href="{% url "users:logout" %}">Logout</a>
                </div>
                </div>

            {% else %}
                <div class="user-dropdown">
            <a class="login" href = "{% url "users:login" %}" > Login </a>
                <div class="dropdown-content">
                    <a href="{% url "users:user_profiles" %}">All users profiles</a>
                </div>
                </div>
            {% endif %}
        </div>
    </header>
    <!-- Nav Bar Code -->
    <div class="nav-bar">
        <ul class="nav-bar-list">
            {% if request.session.username %}
            <li><a href="{% url "tripobeatApp:alternate_page" %}">Home</a></li>
            {% else %}
                <li><a href="{% url "tripobeatApp:home_page" %}">Home</a></li>
            {% endif %}
            <li><a href="{% url "tripobeatApp:category_page" %}">Itineraries</a></li>
            <li><a href="#">Activities</a></li>
            <li><a href="#">Top Rated</a></li>
            <li><a href="{% url "tripobeatApp:blog_page" %}">Blog</a></li>
        </ul>
    </div>
    {% if messages %}
    <ul class="message-content">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <!-- Content div of the Webpage, explains how website works -->
       {% block content-text-block %}{% endblock %}

    <!-- Footer Code -->
    <footer class="footer">
        <div class="footer-left">
            <a href="index.html"> About </a>
            <a href="index.html"> Contact Us </a>
            <a href="index.html"> Rate Us </a>
        </div>
        <div class="footer-center">
            <a>© Tripobeat Technologies Limited</a>
            <a href="index.html">Terms of Service</a>
            <a href="index.html">Privacy Policy </a>
        </div>
        <div class="footer-right">
            <a href="https://www.facebook.com/" class="fa fa-facebook"></a>
            <a href="https://www.instagram.com/" class="fa fa-instagram"></a>
            <a href="https://www.twitter.com/" class="fa fa-twitter"></a>
        </div>
    </footer>
</body>

</html>