tripobeat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tripobeatApp.urls', namespace='tripobeat')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'
#url patterns has list of all urls corresponding to the views and the webpages
urlpatterns = [
    path('', views.login, name = 'login'),
    path('login/', views.login_page, name = 'login_page'),
    path('logout/', views.logout_page, name= 'logout'),
    path('register/', views.register, name = 'register'),
    path('profile/<str:username>', views.profile, name = 'profile'),
    #path('editprofile/<str:username>', views.edit_profile, name = 'edit_profile'),
    path('userprofiles/', views.user_profiles, name = 'user_profiles'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Details(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE)
    role = models.CharField(default = "regular", max_length= 10)
    gender = models.CharField(default = "other", max_length=10)

@receiver(post_save, sender = User)
def create_user_details(sender, instance, created, **kwargs):
    if created:
        Details.objects.create(user =instance)

@receiver(post_save, sender = User)
def save_user_details(sender, instance, **kwargs):
    instance.details.save()

users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from .models import User

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=50, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True,
                               min_length=5)
    email = forms.EmailField(max_length=50, required=True)

    first_name = forms.CharField(max_length=30, required=True, validators=[
        RegexValidator(r'^[a-zA-Z]*$', message="First name should not contain numerics, only alphabets")])
    last_name = forms.CharField(max_length=30, required=True, validators=[
        RegexValidator(r'^[a-zA-Z]*$', message="Last name should not contain numerics, only alphabets")])

    gender = forms.ChoiceField(
        choices=(("Male", "Male"), ("Female", "Female"), ("Other", "Other")),
        widget=forms.RadioSelect(),
        required=True,
    )

class ProfileEditForm(forms.Form):
    password = forms.CharField(widget=forms.TextInput(attrs={'type': 'password'}), required=True, min_length=5)
    email = forms.EmailField(max_length=50, required=True)
    first_name = forms.CharField(max_length=30, required=True, validators=[
        RegexValidator(r'^[a-zA-Z]*$', message="First name should not contain numerics, only alphabets")])
    last_name = forms.CharField(max_length=30, required=True, validators=[
        RegexValidator(r'^[a-zA-Z]*$', message="Last name should not contain numerics, only alphabets")])
    gender = forms.ChoiceField(
        choices=(("Male", "Male"), ("Female", "Female"), ("Other", "Other")),
        widget=forms.RadioSelect(),
        required=True,
    )
    role = forms.CharField(max_length=10, required=False)

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, get_user_model
from django.contrib import messages
from .models import Details
from .forms import RegistrationForm, ProfileEditForm
from actions.models import Action


# login page view is to have login functionality, here credentials are hardcoded. we use this view for login page.
def login(request):
    return render(request, 'users/user/login.html')

def login_page(request):
        error_message = None
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username)
        print(password)
        User = get_user_model()
        #user = authenticate(username = username, password = password)
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            user = None
        if user is not None and (password == user.password):
            request.session['username'] = user.username
            request.session['access'] = user.details.role
            messages.add_message(request, messages.SUCCESS, "You have logged in succesfully")
            return redirect('tripobeatApp:alternate_page')
        else:
            messages.add_message(request, messages.ERROR, "Invalid Credentials, please try again")
        return render(request, 'users/user/login.html')

#logout is to logout for the user. It redirects to the home page after logout
def logout_page(request):
    if 'username' in request.session:
        del request.session['username']
    if 'access' in request.session:
        del request.session['access']
    return redirect('tripobeatApp:home_page')

def profile(request, username):
    user = get_object_or_404(User, username=username)
    details, created = Details.objects.get_or_create(user=user)
    if request.session.get('access') == 'admin' or request.session.get('username') == user.username:
        if request.method == 'POST':
            form = ProfileEditForm(request.POST)
            if form.is_valid():
                # Update user data with the form data
                user.password = form.cleaned_data['password']
                user.email = form.cleaned_data['email']
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                gender = form.cleaned_data['gender']
                user.save()

                if request.session.get('username') != user.username:
                    role = form.cleaned_data['role']
                    old_role = details.role
                    details.role = role
                details.gender = gender
                details.save()
                if request.session.get('username') != user.username:
                    if old_role != form.cleaned_data['role']:
                        action = Action(
                            user=user,
                            verb=" role has been changed from " + old_role + " to " + form.cleaned_data['role'],
                            role_changed=True,
                        )
                        action.save()
                messages.success(request, 'Profile updated successfully.')
        else:
            form = ProfileEditForm(initial={
                'password': user.password,
                'email': user.email,
                'first_name': user.first_name,
                'last_name': user.last_name,
                'gender': user.details.gender if hasattr(user, 'details') else None,
                'role': user.details.role if hasattr(user, 'details') else 'regular',
            })
    else:
        actions = Action.objects.filter(user_id=user.id).order_by('-created')
        return render(request, 'users/user/profile.html', {"user": user, "actions": actions})
    actions = Action.objects.filter(user_id=user.id).order_by('-created')
    return render(request, 'users/user/profile.html', {"user": user, 'form': form, 'actions': actions})


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            gender = form.cleaned_data['gender']

            user = User.objects.create(username=username, email=email, password=password, first_name=first_name,
                                       last_name=last_name)
            details, created = Details.objects.get_or_create(user=user)
            details.gender = gender
            details.save()

            request.session['username'] = user.username
            messages.success(request, f"{user.username} registered successfully")
            return redirect("tripobeatApp:alternate_page")
    else:
        form = RegistrationForm()
    return render(request, 'users/user/register.html', {'form': form})

def user_profiles(request):
    user_names = User.objects.values_list('username', flat=True)
    return render(request, 'users/user/other_profiles.html', {'user_names': user_names})

templates/users/user/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <link rel="stylesheet" href="{% static "css/login.css" %}">
</head>
<body class = "body">
    <div class="login-box">
        <img class="site-logo" alt="site-logo" src="{% static "images/Tripobeat-logo.png" %}">
        <form method="post" action = {% url "users:login_page" %}>
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>

            <button type="submit">Login</button>
            <div class = "signup-div">
            <a href="{% url "users:register" %}" class="signup-text">
                   Not a User? Sign Up.
            </a>
            </div>
        </form>
        {% if messages %}
            <ul class="message-content">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
            </ul>
        {% endif %}
        {% if error_message %}
            <script>
                window.alert("{{ error_message }}");
            </script>
        {% endif %}
    </div>
</body>
</html>

templates/users/user/other_profiles.html
{% extends "tripobeatApp/base.html" %}
{% load static %}

<title>Other Profiles Page</title>
<link rel="stylesheet" href="{% static "css/index.css"%}">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static "js/form.js" %}"></script>

{% block content-text-block %}
    <div class = "user-profiles">
    <div>
    <h2> All User Profiles </h2>
    </div>
    <div class = "profile-list-div">
    <ul class = "profile-list-ul">
        {% for user_name in user_names %}
            <a href="{% url "users:profile" user_name %}"><li class = "profile-list">{{ user_name }}</li></a>
        {% endfor %}
    </ul>
    </div>
    </div>
{% endblock %}

templates/users/user/profile.html
{% extends "tripobeatApp/base.html" %}
{% load static %}

<title>Profile Page</title>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

{% block content-text-block %}
    <div class = "single-profile-div">
    <div>
    <h2> Profile Page for {{ user.username }} </h2>
    </div>
    <div class = "profile-main-div">
    {% if request.session.access == 'admin' or request.session.username == user.username%}
    <div>
<form id="profile-form" class="profile-form" action="{% url 'users:profile' username=user.username %}" method="post">
    {% csrf_token %}
    <div>Username: {{ user.username }}</div>
    {% for field in form %}
        {% if field.name != 'role' %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                {{ field }}
                {{ field.errors }}
            </div>
        {% endif %}
    {% endfor %}
    {% if request.session.access == "admin" %}
        <label for="{{ form.role.id_for_label }}">Role</label>
        {{ form.role }}
        {{ form.role.errors }}
    {% endif %}
    <div class = "profile-submit"><button class = "profile-submit-button" type="submit" id="save-btn">Save</button></div>
</form>
    </div>
    {% else %}
        <div class = "non-editable-profile">
        <div>Username: {{ user.username }}</div>
        <div>First Name: {{ user.first_name }}</div>
        <div>Last Name: {{ user.last_name }}</div>
        <div>Email: {{ user.email }}</div>
        </div>
    {% endif %}
    <div class ="recent-activity">
{% include "actions/action/feed.html" %}
    </div>
    </div>

    </div>
{% endblock %}

templates/users/user/profile_view.html
{% extends "tripobeatApp/base.html" %}
{% load static %}

<title>Profile Page</title>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

{% block content-text-block %}
    <div class = "single-profile-div">
    <div>
    <h2> Profile Page for {{ user.username }} </h2>
    </div>
         {{ user.username }}
    {{ user.first_name }}
        {{ user.last_name }}
        {{ user.email }}
        {{ user.gender }}
    </div>
{% endblock %}

templates/users/user/register.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Register Page</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src= "{% static "js/login.js" %}" ></script>
    <link rel="stylesheet" href="{% static "css/login.css"%}">
</head>
<body class = "body">
    <div class="login-box">
        <img class="site-logo" alt="site-logo" src="{% static "images/Tripobeat-logo.png" %}">
        <form method="post" action="{% url 'users:register' %}">
            {% csrf_token %}
            {{ form.as_div }}
        <button type="submit">Register</button>
            <div class = "login-link"><a href = "{% url 'users:login' %}"> Return to Login </a></div>
        </form>
        {% if error_message %}
            <script>
                window.alert("{{ error_message }}");
            </script>
        {% endif %}
    </div>
</body>
</html>